### ISSUE TITLE
CoreNLPServerError: Status code: [500] (edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl)

### ISSUE THREAD

**Issue by hexingren** [sina-al/pynlp#12]
Hello,

I received CoreNLPServerError when trying to make it work with Version 3.9.1 of CoreNLP. Does it support the latest version for NER? Thanks!

**Comment by sina-al** [comment]
Hey,

What version of Java do you have installed?

**Comment by hexingren** [comment]
I was using Java 9 and CoreNLP v3.9.1. 

It turned out that something happened to the NER tagger on the  CoreNLP server side. The error message below pops out when I try to tag any sentence using the NER tagger via the web interface on http://localhost:9000.

"""
edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl
"""

**Comment by sina-al** [comment]
Try running the CoreNLP server as instructed [here](https://stanfordnlp.github.io/CoreNLP/corenlp-server.html) but also add the flag 
```
--add-modules java.se.ee
```

There's no way to do this via `pynlp` currently but I will add it soon.

Alternatively you can use Java 8

**Comment by sina-al** [comment]
Can you try using appending the following option when constructing your `pynlp.client.StanfordCoreNLP` object

```python
annotators = 'ner, ' # + your other annotators
options = {"ner.useSUTime": False}

nlp = StanfordCoreNLP(annotators=annotators, options=options)
```

**Comment by hexingren** [comment]
Nice catch!!! It worked.

Could you elaborate the magic here? What is useSUTime and why does it matter? Was the problem on the server side or the wrapper? I tried every Python wrapper of CoreNLP online and they all failed on NER (but worked for other annotators). Really want to know the reasons. Many thanks!

**Comment by sina-al** [comment]
I'm not too sure to be honest. I based the suggestion off a [closed issue](https://github.com/stanfordnlp/CoreNLP/issues/636) on the original repository. 
For more info I would probably suggest opening an issue on the CoreNLP repository directly.

Thanks
