### ISSUE TITLE
ModuleNotFoundError: No module named 'pynlp'

### ISSUE THREAD

**Issue by kaschioudi** [sina-al/pynlp#7]
Hello,

I have followed the instructions in the README and installed the library via `pip3 install pynlp`. 

When I go to the prompt and execute `from pynlp import StanfordCoreNLP` I get the following error:

```
>>> from pynlp import StanfordCoreNLP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pynlp'
```

Is there something i am doing wrong?

Thank you for your assistance,

**Comment by sina-al** [comment]
Hi,

What version of python are you using when you get this error?

**Comment by sina-al** [comment]
Closed as abandoned.
