### ISSUE TITLE
gives IndexError when i use nlp(text)

### ISSUE THREAD

**Issue by mcjoshi** [sina-al/pynlp#9]
Hi, I followed up the demo you have given. But it doesn't work.
![aa](https://user-images.githubusercontent.com/33366571/35991491-5abcb000-0d2d-11e8-9b5b-0b6632c671d8.png)

What am i missing ?

**Comment by sina-al** [comment]
Hi mcjoshi, thanks for this. What version of Stanford CoreNLP are you using? I can't seem to reproduce this error with version 3.8. It's possible that the library isn't compatible with the new 3.9 release. If so, try using 3.8 for now. Let me know how it goes, thanks.

**Comment by mcjoshi** [comment]
I tried it with 3.6, 3.8 and 3.9. So I don't think its problem related to CoreNLP version. I tried it using `pycorenlp` for entity recognition. It works fine when **ner** is excluded and when **ner** is included in annotators, it gives error.

When i run following section of your code, it prints nothing : 
```
from pynlp import StanfordCoreNLP
nlp = StanfordCoreNLP(annotators='entitymentions')
text
``` = ('GOP Sen. Rand Paul was assaulted in his home.')
doc = nlp(text)
print(doc)

**Comment by mcjoshi** [comment]
I tried it with 3.6, 3.8 and 3.9. So I don't think its problem related to CoreNLP version. I tried doing entity recognition using `pycorenlp`. It works fine when **ner** is excluded but when **ner** is included in annotators, it gives error.

When i run following section of your code, it prints nothing : 
```
from pynlp import StanfordCoreNLP
nlp = StanfordCoreNLP(annotators='entitymentions')
text = ('GOP Sen. Rand Paul was assaulted in his home.')
doc = nlp(text)
print(doc)

**Comment by sina-al** [comment]
Can you please show me the output of the following code:

```python
from pynlp import StanfordCoreNLP
nlp = StanfordCoreNLP(annotators='entitymentions')
text = ('GOP Sen. Rand Paul was assaulted in his home.')
doc = nlp(text)
print(doc._doc)
```

Also, please run pip freeze and paste here the version numbers for:
* corenlp_protobuf
* pynlp

**Comment by TMarafon** [comment]
Hi, I'm having the same issue here. 

```
from pynlp import StanfordCoreNLP
nlp = StanfordCoreNLP(annotators='entitymentions')
text = ('GOP Sen. Rand Paul was assaulted in his home.')
doc = nlp(text)
print(doc._doc)
```
The output is empty.

Regarding the version numbers:

- corenlp_protobuf: 3.7.1
- pynlp: 0.3.5

**Comment by sina-al** [comment]
Hello,

I'm not quite sure why this is happening. Could you try using the latest version from github?
`pip3 install git+https://github.com/sina-al/pynlp --upgrade`

**Comment by sina-al** [comment]
Closed as abandoned.
